// automatically generated by the FlatBuffers compiler, do not modify

package game

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ActorDelete struct {
	_tab flatbuffers.Table
}

func GetRootAsActorDelete(buf []byte, offset flatbuffers.UOffsetT) *ActorDelete {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ActorDelete{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ActorDelete) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ActorDelete) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ActorDelete) Auth(obj *Token) *Token {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Token)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ActorDelete) Subset(obj *ActorSubset) *ActorSubset {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ActorSubset)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ActorDeleteStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ActorDeleteAddAuth(builder *flatbuffers.Builder, auth flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(auth), 0)
}
func ActorDeleteAddSubset(builder *flatbuffers.Builder, subset flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(subset), 0)
}
func ActorDeleteEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
