version: "3"
services:

  # Redis
  redis:
    build: docker/redis
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
    ports:
      - 6379:6379

  # Redis-LRU
  redis-lru:
    build: docker/redis
    volumes:
      - ./docker/redis/redis-lru.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
    ports:
      - 6380:6379

  # API
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    volumes:
      - ./config/api.json:/app/api.json
    expose:
      - 3400
    ports:
      - 3400:3400/udp
    links:
      - redis
      - redis-lru
    network_mode: "host"

  # Auth
  auth:
    build:
      context: .
      dockerfile: docker/auth/Dockerfile
    volumes:
      - ./config/auth.json:/app/auth.json
      - ./config/server.crt:/app/server.crt
      - ./config/server.key:/app/server.key
    expose:
      - 8080
    ports:
      - 8080:8080
    links:
      - redis
      - redis-lru

  # Client
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    volumes:
      - ./config/client.json:/app/client.json
    expose:
      - 42000
      - 42001
    ports:
      - 42000:42000/udp
      - 42001:42001/udp
    links:
      - api
      - sync

  # Core
  core:
    build:
      context: .
      dockerfile: docker/core/Dockerfile
    volumes:
      - ./config/core.json:/app/core.json
    links:
      - redis
      - redis-lru

  # Revoker
  revoker:
    build:
      context: .
      dockerfile: docker/revoker/Dockerfile
    volumes:
      - ./config/revoker.json:/app/revoker.json
    links:
      - redis
      - redis-lru

  # # Sandbox
  # sandbox:
  #   build:
  #     context: .
  #     dockerfile: docker/sandbox/Dockerfile
  #   volumes:
  #     - ./config/sandbox.json:/app/sandbox.json
  #     - ./cmd/sandbox/assets:/app/assets
  #   expose:
  #     - 42000
  #     - 42001
  #   ports:
  #     - 42000:42000/udp
  #     - 42001:42001/udp
  #   links:
  #     - api
  #     - sync

  # Sync
  sync:
    build:
      context: .
      dockerfile: docker/sync/Dockerfile
    volumes:
      - ./config/sync.json:/app/sync.json
    links:
      - redis
      - redis-lru

  # Tool
  tool:
    build:
      context: .
      dockerfile: docker/tool/Dockerfile
    volumes:
      - ./config/tool.json:/app/tool.json
      - ./config/server.crt:/app/server.crt
      - ./config/server.key:/app/server.key
    expose:
      - 8081
    ports:
      - 8081:8081
    links:
      - redis
      - redis-lru
