version: "3"
services:

  # Redis
  redis:
    build: docker/redis
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379

  # Redis-LRU
  redis-lru:
    build: docker/redis
    volumes:
      - ./docker/redis/redis-lru.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6380:6379

  # API
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    volumes:
      - ./config/api.json:/app/api.json
    ports:
      - 3400:3400
    links:
      - redis
      - redis-lru

  # Auth
  auth:
    build:
      context: .
      dockerfile: docker/auth/Dockerfile
    volumes:
      - ./config/auth.json:/app/auth.json
    ports:
      - 8080:8080
    links:
      - redis
      - redis-lru

  # Client
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    volumes:
      - ./config/client.json:/app/client.json
    ports:
      - 42000:42000
      - 42001:42001
    links:
      - redis
      - redis-lru

  # Core
  core:
    build:
      context: .
      dockerfile: docker/core/Dockerfile
    volumes:
      - ./config/core.json:/app/core.json
    ports:
      - 8080:8080
    links:
      - redis
      - redis-lru

  # Integration
  integration:
    build:
      context: .
      dockerfile: docker/integration/Dockerfile
    volumes:
      - ./config/integration.json:/app/integration.json
    ports:
      - 8080:8080
    links:
      - redis
      - redis-lru

  # Revoker
  revoker:
    build:
      context: .
      dockerfile: docker/revoker/Dockerfile
    volumes:
      - ./config/revoker.json:/app/revoker.json
    ports:
      - 8080:8080
    links:
      - redis
      - redis-lru

  # Sync
  sync:
    build:
      context: .
      dockerfile: docker/sync/Dockerfile
    volumes:
      - ./config/sync.json:/app/sync.json
    ports:
      - 8080:8080
    links:
      - redis
      - redis-lru

  # Tool
  tool:
    build:
      context: .
      dockerfile: docker/tool/Dockerfile
    volumes:
      - ./config/tool.json:/app/tool.json
    ports:
      - 8080:8080
    links:
      - redis
      - redis-lru
