version: "3"
services:

  # Redis
  redis:
    build: docker/redis
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379

  # Redis-LRU
  redis-lru:
    build: docker/redis
    volumes:
      - ./docker/redis/redis-lru.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6380:6380
