version: "3"
services:

  # Redis
  redis:
    build: docker/redis
    ports:
      - 6379:6379

  # NATS
  nats:
    image: nats
    ports:
      - 4222:4222
      - 8222:8222

  # Tile38
  tile38:
    image: tile38/tile38
    ports:
      - 9851:9851
