[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "github.com/cloudflare/golz4"
    unused-packages = false

  [[prune.project]]
    name = "github.com/go-gl/glfw"
    unused-packages = false
