// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ability.proto

package ability

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import github_com_elojah_game_01_pkg_ulid "github.com/elojah/game_01/pkg/ulid"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type A struct {
	ID                   github_com_elojah_game_01_pkg_ulid.ID `protobuf:"bytes,1,opt,name=ID,json=iD,proto3,customtype=github.com/elojah/game_01/pkg/ulid.ID" json:"ID"`
	Type                 github_com_elojah_game_01_pkg_ulid.ID `protobuf:"bytes,2,opt,name=Type,json=type,proto3,customtype=github.com/elojah/game_01/pkg/ulid.ID" json:"Type"`
	Name                 string                                `protobuf:"bytes,3,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	MPConsumption        uint64                                `protobuf:"varint,4,opt,name=MPConsumption,json=mPConsumption,proto3" json:"MPConsumption,omitempty"`
	CD                   uint32                                `protobuf:"varint,5,opt,name=CD,json=cD,proto3" json:"CD,omitempty"`
	CurrentCD            uint32                                `protobuf:"varint,6,opt,name=CurrentCD,json=currentCD,proto3" json:"CurrentCD,omitempty"`
	CastTime             uint32                                `protobuf:"varint,7,opt,name=CastTime,json=castTime,proto3" json:"CastTime,omitempty"`
	Components           []Component                           `protobuf:"bytes,8,rep,name=Components,json=components" json:"Components"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *A) Reset()      { *m = A{} }
func (*A) ProtoMessage() {}
func (*A) Descriptor() ([]byte, []int) {
	return fileDescriptor_ability_33b557a465aeb921, []int{0}
}
func (m *A) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *A) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_A.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *A) XXX_Merge(src proto.Message) {
	xxx_messageInfo_A.Merge(dst, src)
}
func (m *A) XXX_Size() int {
	return m.Size()
}
func (m *A) XXX_DiscardUnknown() {
	xxx_messageInfo_A.DiscardUnknown(m)
}

var xxx_messageInfo_A proto.InternalMessageInfo

func (m *A) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *A) GetMPConsumption() uint64 {
	if m != nil {
		return m.MPConsumption
	}
	return 0
}

func (m *A) GetCD() uint32 {
	if m != nil {
		return m.CD
	}
	return 0
}

func (m *A) GetCurrentCD() uint32 {
	if m != nil {
		return m.CurrentCD
	}
	return 0
}

func (m *A) GetCastTime() uint32 {
	if m != nil {
		return m.CastTime
	}
	return 0
}

func (m *A) GetComponents() []Component {
	if m != nil {
		return m.Components
	}
	return nil
}

func init() {
	proto.RegisterType((*A)(nil), "A")
}
func (this *A) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*A)
	if !ok {
		that2, ok := that.(A)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ID.Equal(that1.ID) {
		return false
	}
	if !this.Type.Equal(that1.Type) {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.MPConsumption != that1.MPConsumption {
		return false
	}
	if this.CD != that1.CD {
		return false
	}
	if this.CurrentCD != that1.CurrentCD {
		return false
	}
	if this.CastTime != that1.CastTime {
		return false
	}
	if len(this.Components) != len(that1.Components) {
		return false
	}
	for i := range this.Components {
		if !this.Components[i].Equal(&that1.Components[i]) {
			return false
		}
	}
	return true
}
func (this *A) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 12)
	s = append(s, "&ability.A{")
	s = append(s, "ID: "+fmt.Sprintf("%#v", this.ID)+",\n")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "MPConsumption: "+fmt.Sprintf("%#v", this.MPConsumption)+",\n")
	s = append(s, "CD: "+fmt.Sprintf("%#v", this.CD)+",\n")
	s = append(s, "CurrentCD: "+fmt.Sprintf("%#v", this.CurrentCD)+",\n")
	s = append(s, "CastTime: "+fmt.Sprintf("%#v", this.CastTime)+",\n")
	if this.Components != nil {
		vs := make([]*Component, len(this.Components))
		for i := range vs {
			vs[i] = &this.Components[i]
		}
		s = append(s, "Components: "+fmt.Sprintf("%#v", vs)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringAbility(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *A) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *A) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintAbility(dAtA, i, uint64(m.ID.Size()))
	n1, err := m.ID.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	dAtA[i] = 0x12
	i++
	i = encodeVarintAbility(dAtA, i, uint64(m.Type.Size()))
	n2, err := m.Type.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	if len(m.Name) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintAbility(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if m.MPConsumption != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintAbility(dAtA, i, uint64(m.MPConsumption))
	}
	if m.CD != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintAbility(dAtA, i, uint64(m.CD))
	}
	if m.CurrentCD != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintAbility(dAtA, i, uint64(m.CurrentCD))
	}
	if m.CastTime != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintAbility(dAtA, i, uint64(m.CastTime))
	}
	if len(m.Components) > 0 {
		for _, msg := range m.Components {
			dAtA[i] = 0x42
			i++
			i = encodeVarintAbility(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func encodeVarintAbility(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *A) Size() (n int) {
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovAbility(uint64(l))
	l = m.Type.Size()
	n += 1 + l + sovAbility(uint64(l))
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovAbility(uint64(l))
	}
	if m.MPConsumption != 0 {
		n += 1 + sovAbility(uint64(m.MPConsumption))
	}
	if m.CD != 0 {
		n += 1 + sovAbility(uint64(m.CD))
	}
	if m.CurrentCD != 0 {
		n += 1 + sovAbility(uint64(m.CurrentCD))
	}
	if m.CastTime != 0 {
		n += 1 + sovAbility(uint64(m.CastTime))
	}
	if len(m.Components) > 0 {
		for _, e := range m.Components {
			l = e.Size()
			n += 1 + l + sovAbility(uint64(l))
		}
	}
	return n
}

func sovAbility(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozAbility(x uint64) (n int) {
	return sovAbility(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *A) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&A{`,
		`ID:` + fmt.Sprintf("%v", this.ID) + `,`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`MPConsumption:` + fmt.Sprintf("%v", this.MPConsumption) + `,`,
		`CD:` + fmt.Sprintf("%v", this.CD) + `,`,
		`CurrentCD:` + fmt.Sprintf("%v", this.CurrentCD) + `,`,
		`CastTime:` + fmt.Sprintf("%v", this.CastTime) + `,`,
		`Components:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Components), "Component", "Component", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringAbility(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *A) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAbility
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: A: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: A: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAbility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAbility
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAbility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAbility
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Type.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAbility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAbility
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MPConsumption", wireType)
			}
			m.MPConsumption = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAbility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MPConsumption |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CD", wireType)
			}
			m.CD = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAbility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CD |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentCD", wireType)
			}
			m.CurrentCD = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAbility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentCD |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CastTime", wireType)
			}
			m.CastTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAbility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CastTime |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Components", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAbility
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAbility
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Components = append(m.Components, Component{})
			if err := m.Components[len(m.Components)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAbility(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAbility
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAbility(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAbility
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAbility
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAbility
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthAbility
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowAbility
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipAbility(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthAbility = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAbility   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("ability.proto", fileDescriptor_ability_33b557a465aeb921) }

var fileDescriptor_ability_33b557a465aeb921 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xbd, 0x4e, 0xe3, 0x40,
	0x14, 0x85, 0x7d, 0x1d, 0x6f, 0x7e, 0x66, 0xd7, 0xbb, 0xd2, 0x54, 0xa3, 0x68, 0x35, 0xb1, 0x56,
	0xbb, 0x92, 0x9b, 0xd8, 0xd9, 0xdd, 0x3a, 0x45, 0x62, 0x37, 0x29, 0x40, 0xc8, 0x4a, 0x45, 0x83,
	0x6c, 0x33, 0x38, 0x86, 0x8c, 0xc7, 0x8a, 0xc7, 0x45, 0x3a, 0x1e, 0x81, 0xc7, 0xe0, 0x11, 0x90,
	0x68, 0x28, 0x53, 0xa6, 0x44, 0x14, 0x11, 0x19, 0x1a, 0xca, 0x3c, 0x02, 0xc2, 0x24, 0x51, 0x6a,
	0xba, 0x7b, 0xbe, 0x7b, 0x75, 0xa4, 0x7b, 0x0e, 0x32, 0xc3, 0x28, 0x9d, 0xa6, 0x72, 0xee, 0xe4,
	0x33, 0x21, 0x45, 0xbb, 0x9b, 0xa4, 0x72, 0x52, 0x46, 0x4e, 0x2c, 0xb8, 0x9b, 0x88, 0x44, 0xb8,
	0x15, 0x8e, 0xca, 0x8b, 0x4a, 0x55, 0xa2, 0x9a, 0xb6, 0xe7, 0x3f, 0x62, 0xc1, 0x73, 0x91, 0xb1,
	0x4c, 0x7e, 0x80, 0x5f, 0xf7, 0x3a, 0x82, 0x01, 0xee, 0x23, 0x7d, 0xe4, 0x13, 0xb0, 0xc0, 0xfe,
	0x36, 0xec, 0x2e, 0x56, 0x1d, 0xed, 0x69, 0xd5, 0xf9, 0x73, 0xe0, 0xcc, 0xa6, 0xe2, 0x32, 0x9c,
	0xb8, 0x49, 0xc8, 0xd9, 0x59, 0xef, 0xaf, 0x9b, 0x5f, 0x25, 0x6e, 0x39, 0x4d, 0xcf, 0x9d, 0x91,
	0x1f, 0xe8, 0xa9, 0x8f, 0x07, 0xc8, 0x18, 0xcf, 0x73, 0x46, 0xf4, 0xcf, 0x18, 0x18, 0x72, 0x9e,
	0x33, 0x8c, 0x91, 0x71, 0x1c, 0x72, 0x46, 0x6a, 0x16, 0xd8, 0xad, 0xc0, 0xc8, 0x42, 0xce, 0xf0,
	0x6f, 0x64, 0x1e, 0x9d, 0x78, 0x22, 0x2b, 0x4a, 0x9e, 0xcb, 0x54, 0x64, 0xc4, 0xb0, 0xc0, 0x36,
	0x02, 0x93, 0x1f, 0x42, 0xfc, 0x1d, 0xe9, 0x9e, 0x4f, 0xbe, 0x58, 0x60, 0x9b, 0x81, 0x1e, 0xfb,
	0xf8, 0x27, 0x6a, 0x79, 0xe5, 0x6c, 0xc6, 0x32, 0xe9, 0xf9, 0xa4, 0x5e, 0xe1, 0x56, 0xbc, 0x03,
	0xb8, 0x8d, 0x9a, 0x5e, 0x58, 0xc8, 0x71, 0xca, 0x19, 0x69, 0x54, 0xcb, 0x66, 0xbc, 0xd5, 0xb8,
	0x87, 0x90, 0xb7, 0x8b, 0xa7, 0x20, 0x4d, 0xab, 0x66, 0x7f, 0xfd, 0x87, 0x9c, 0x3d, 0x1a, 0x1a,
	0xef, 0x8f, 0x05, 0x68, 0x1f, 0x61, 0x31, 0xec, 0x2f, 0xd7, 0x54, 0x7b, 0x5c, 0x53, 0x6d, 0xb3,
	0xa6, 0x70, 0xad, 0x28, 0xdc, 0x2a, 0x0a, 0x77, 0x8a, 0xc2, 0x83, 0xa2, 0xb0, 0x50, 0x14, 0x96,
	0x8a, 0xc2, 0xb3, 0xa2, 0xf0, 0xaa, 0xa8, 0xb6, 0x51, 0x14, 0x6e, 0x5e, 0xa8, 0x76, 0xda, 0xd8,
	0x56, 0x18, 0xd5, 0xab, 0x0e, 0xfe, 0xbf, 0x05, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x9a, 0x0d, 0x59,
	0xd4, 0x01, 0x00, 0x00,
}
