version: 2

jobs:

  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/elojah/game_01
    steps:
      - checkout
      - run:
          name: dependencies
          command: make vendor
          environment:
            GO111MODULE: on

  test:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/elojah/game_01
    steps:
      - checkout
      - run:
          name: unit tests
          command: make check

  deploy:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
