version: 2

jobs:

  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/elojah/game_01
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: make vendor

  test:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/elojah/game_01
    steps:
      - checkout
      - run:
          name: Install linters
          command: go get -u github.com/alecthomas/gometalinter && gometalinter --install
      - run:
          name: Run unit
          command: make check

  deploy:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
