// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dto.proto

package event

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import ability "github.com/elojah/game_01/pkg/ability"
import geometry "github.com/elojah/game_01/pkg/geometry"
import _ "github.com/gogo/protobuf/gogoproto"

import github_com_elojah_game_01_pkg_ulid "github.com/elojah/game_01/pkg/ulid"

import strings "strings"
import reflect "reflect"
import github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Move struct {
	Targets              []github_com_elojah_game_01_pkg_ulid.ID `protobuf:"bytes,1,rep,name=Targets,json=targets,customtype=github.com/elojah/game_01/pkg/ulid.ID" json:"Targets"`
	Position             geometry.Position                       `protobuf:"bytes,2,opt,name=Position,json=position" json:"Position"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *Move) Reset()      { *m = Move{} }
func (*Move) ProtoMessage() {}
func (*Move) Descriptor() ([]byte, []int) {
	return fileDescriptor_dto_1b53a3328885b6b6, []int{0}
}
func (m *Move) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Move) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Move.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Move) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Move.Merge(dst, src)
}
func (m *Move) XXX_Size() int {
	return m.Size()
}
func (m *Move) XXX_DiscardUnknown() {
	xxx_messageInfo_Move.DiscardUnknown(m)
}

var xxx_messageInfo_Move proto.InternalMessageInfo

func (m *Move) GetPosition() geometry.Position {
	if m != nil {
		return m.Position
	}
	return geometry.Position{}
}

type Cast struct {
	Source               github_com_elojah_game_01_pkg_ulid.ID `protobuf:"bytes,1,opt,name=Source,json=source,proto3,customtype=github.com/elojah/game_01/pkg/ulid.ID" json:"Source"`
	AbilityID            github_com_elojah_game_01_pkg_ulid.ID `protobuf:"bytes,2,opt,name=AbilityID,json=abilityID,proto3,customtype=github.com/elojah/game_01/pkg/ulid.ID" json:"AbilityID"`
	Targets              map[string]ability.Targets            `protobuf:"bytes,3,rep,name=Targets,json=targets" json:"Targets" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *Cast) Reset()      { *m = Cast{} }
func (*Cast) ProtoMessage() {}
func (*Cast) Descriptor() ([]byte, []int) {
	return fileDescriptor_dto_1b53a3328885b6b6, []int{1}
}
func (m *Cast) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Cast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Cast.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Cast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cast.Merge(dst, src)
}
func (m *Cast) XXX_Size() int {
	return m.Size()
}
func (m *Cast) XXX_DiscardUnknown() {
	xxx_messageInfo_Cast.DiscardUnknown(m)
}

var xxx_messageInfo_Cast proto.InternalMessageInfo

func (m *Cast) GetTargets() map[string]ability.Targets {
	if m != nil {
		return m.Targets
	}
	return nil
}

type Loot struct {
	Source               github_com_elojah_game_01_pkg_ulid.ID `protobuf:"bytes,1,opt,name=Source,json=source,proto3,customtype=github.com/elojah/game_01/pkg/ulid.ID" json:"Source"`
	TargetID             github_com_elojah_game_01_pkg_ulid.ID `protobuf:"bytes,2,opt,name=TargetID,json=targetID,proto3,customtype=github.com/elojah/game_01/pkg/ulid.ID" json:"TargetID"`
	ItemID               github_com_elojah_game_01_pkg_ulid.ID `protobuf:"bytes,3,opt,name=ItemID,json=itemID,proto3,customtype=github.com/elojah/game_01/pkg/ulid.ID" json:"ItemID"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *Loot) Reset()      { *m = Loot{} }
func (*Loot) ProtoMessage() {}
func (*Loot) Descriptor() ([]byte, []int) {
	return fileDescriptor_dto_1b53a3328885b6b6, []int{2}
}
func (m *Loot) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Loot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Loot.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Loot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Loot.Merge(dst, src)
}
func (m *Loot) XXX_Size() int {
	return m.Size()
}
func (m *Loot) XXX_DiscardUnknown() {
	xxx_messageInfo_Loot.DiscardUnknown(m)
}

var xxx_messageInfo_Loot proto.InternalMessageInfo

type Consume struct {
	Source               github_com_elojah_game_01_pkg_ulid.ID `protobuf:"bytes,1,opt,name=Source,json=source,proto3,customtype=github.com/elojah/game_01/pkg/ulid.ID" json:"Source"`
	TargetID             github_com_elojah_game_01_pkg_ulid.ID `protobuf:"bytes,2,opt,name=TargetID,json=targetID,proto3,customtype=github.com/elojah/game_01/pkg/ulid.ID" json:"TargetID"`
	ItemID               github_com_elojah_game_01_pkg_ulid.ID `protobuf:"bytes,3,opt,name=ItemID,json=itemID,proto3,customtype=github.com/elojah/game_01/pkg/ulid.ID" json:"ItemID"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *Consume) Reset()      { *m = Consume{} }
func (*Consume) ProtoMessage() {}
func (*Consume) Descriptor() ([]byte, []int) {
	return fileDescriptor_dto_1b53a3328885b6b6, []int{3}
}
func (m *Consume) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Consume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Consume.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Consume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consume.Merge(dst, src)
}
func (m *Consume) XXX_Size() int {
	return m.Size()
}
func (m *Consume) XXX_DiscardUnknown() {
	xxx_messageInfo_Consume.DiscardUnknown(m)
}

var xxx_messageInfo_Consume proto.InternalMessageInfo

type Query struct {
	Move                 *Move    `protobuf:"bytes,1,opt,name=Move,json=move" json:"Move,omitempty"`
	Cast                 *Cast    `protobuf:"bytes,2,opt,name=Cast,json=cast" json:"Cast,omitempty"`
	Loot                 *Loot    `protobuf:"bytes,3,opt,name=Loot,json=loot" json:"Loot,omitempty"`
	Consume              *Consume `protobuf:"bytes,4,opt,name=Consume,json=consume" json:"Consume,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()      { *m = Query{} }
func (*Query) ProtoMessage() {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_dto_1b53a3328885b6b6, []int{4}
}
func (m *Query) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Query.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(dst, src)
}
func (m *Query) XXX_Size() int {
	return m.Size()
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetMove() *Move {
	if m != nil {
		return m.Move
	}
	return nil
}

func (m *Query) GetCast() *Cast {
	if m != nil {
		return m.Cast
	}
	return nil
}

func (m *Query) GetLoot() *Loot {
	if m != nil {
		return m.Loot
	}
	return nil
}

func (m *Query) GetConsume() *Consume {
	if m != nil {
		return m.Consume
	}
	return nil
}

type DTO struct {
	ID                   github_com_elojah_game_01_pkg_ulid.ID `protobuf:"bytes,1,opt,name=ID,json=iD,proto3,customtype=github.com/elojah/game_01/pkg/ulid.ID" json:"ID"`
	Token                github_com_elojah_game_01_pkg_ulid.ID `protobuf:"bytes,2,opt,name=Token,json=token,proto3,customtype=github.com/elojah/game_01/pkg/ulid.ID" json:"Token"`
	Query                Query                                 `protobuf:"bytes,3,opt,name=Query,json=query" json:"Query"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *DTO) Reset()      { *m = DTO{} }
func (*DTO) ProtoMessage() {}
func (*DTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_dto_1b53a3328885b6b6, []int{5}
}
func (m *DTO) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DTO.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *DTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DTO.Merge(dst, src)
}
func (m *DTO) XXX_Size() int {
	return m.Size()
}
func (m *DTO) XXX_DiscardUnknown() {
	xxx_messageInfo_DTO.DiscardUnknown(m)
}

var xxx_messageInfo_DTO proto.InternalMessageInfo

func (m *DTO) GetQuery() Query {
	if m != nil {
		return m.Query
	}
	return Query{}
}

func init() {
	proto.RegisterType((*Move)(nil), "event.Move")
	proto.RegisterType((*Cast)(nil), "event.Cast")
	proto.RegisterMapType((map[string]ability.Targets)(nil), "event.Cast.TargetsEntry")
	proto.RegisterType((*Loot)(nil), "event.Loot")
	proto.RegisterType((*Consume)(nil), "event.Consume")
	proto.RegisterType((*Query)(nil), "event.Query")
	proto.RegisterType((*DTO)(nil), "event.DTO")
}
func (this *Move) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Move)
	if !ok {
		that2, ok := that.(Move)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Targets) != len(that1.Targets) {
		return false
	}
	for i := range this.Targets {
		if !this.Targets[i].Equal(that1.Targets[i]) {
			return false
		}
	}
	if !this.Position.Equal(&that1.Position) {
		return false
	}
	return true
}
func (this *Cast) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Cast)
	if !ok {
		that2, ok := that.(Cast)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Source.Equal(that1.Source) {
		return false
	}
	if !this.AbilityID.Equal(that1.AbilityID) {
		return false
	}
	if len(this.Targets) != len(that1.Targets) {
		return false
	}
	for i := range this.Targets {
		a := this.Targets[i]
		b := that1.Targets[i]
		if !(&a).Equal(&b) {
			return false
		}
	}
	return true
}
func (this *Loot) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Loot)
	if !ok {
		that2, ok := that.(Loot)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Source.Equal(that1.Source) {
		return false
	}
	if !this.TargetID.Equal(that1.TargetID) {
		return false
	}
	if !this.ItemID.Equal(that1.ItemID) {
		return false
	}
	return true
}
func (this *Consume) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Consume)
	if !ok {
		that2, ok := that.(Consume)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Source.Equal(that1.Source) {
		return false
	}
	if !this.TargetID.Equal(that1.TargetID) {
		return false
	}
	if !this.ItemID.Equal(that1.ItemID) {
		return false
	}
	return true
}
func (this *Query) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Query)
	if !ok {
		that2, ok := that.(Query)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Move.Equal(that1.Move) {
		return false
	}
	if !this.Cast.Equal(that1.Cast) {
		return false
	}
	if !this.Loot.Equal(that1.Loot) {
		return false
	}
	if !this.Consume.Equal(that1.Consume) {
		return false
	}
	return true
}
func (this *DTO) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DTO)
	if !ok {
		that2, ok := that.(DTO)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ID.Equal(that1.ID) {
		return false
	}
	if !this.Token.Equal(that1.Token) {
		return false
	}
	if !this.Query.Equal(&that1.Query) {
		return false
	}
	return true
}
func (this *Move) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&event.Move{")
	s = append(s, "Targets: "+fmt.Sprintf("%#v", this.Targets)+",\n")
	s = append(s, "Position: "+strings.Replace(this.Position.GoString(), `&`, ``, 1)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Cast) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&event.Cast{")
	s = append(s, "Source: "+fmt.Sprintf("%#v", this.Source)+",\n")
	s = append(s, "AbilityID: "+fmt.Sprintf("%#v", this.AbilityID)+",\n")
	keysForTargets := make([]string, 0, len(this.Targets))
	for k, _ := range this.Targets {
		keysForTargets = append(keysForTargets, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForTargets)
	mapStringForTargets := "map[string]ability.Targets{"
	for _, k := range keysForTargets {
		mapStringForTargets += fmt.Sprintf("%#v: %#v,", k, this.Targets[k])
	}
	mapStringForTargets += "}"
	if this.Targets != nil {
		s = append(s, "Targets: "+mapStringForTargets+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Loot) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&event.Loot{")
	s = append(s, "Source: "+fmt.Sprintf("%#v", this.Source)+",\n")
	s = append(s, "TargetID: "+fmt.Sprintf("%#v", this.TargetID)+",\n")
	s = append(s, "ItemID: "+fmt.Sprintf("%#v", this.ItemID)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Consume) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&event.Consume{")
	s = append(s, "Source: "+fmt.Sprintf("%#v", this.Source)+",\n")
	s = append(s, "TargetID: "+fmt.Sprintf("%#v", this.TargetID)+",\n")
	s = append(s, "ItemID: "+fmt.Sprintf("%#v", this.ItemID)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Query) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&event.Query{")
	if this.Move != nil {
		s = append(s, "Move: "+fmt.Sprintf("%#v", this.Move)+",\n")
	}
	if this.Cast != nil {
		s = append(s, "Cast: "+fmt.Sprintf("%#v", this.Cast)+",\n")
	}
	if this.Loot != nil {
		s = append(s, "Loot: "+fmt.Sprintf("%#v", this.Loot)+",\n")
	}
	if this.Consume != nil {
		s = append(s, "Consume: "+fmt.Sprintf("%#v", this.Consume)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DTO) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&event.DTO{")
	s = append(s, "ID: "+fmt.Sprintf("%#v", this.ID)+",\n")
	s = append(s, "Token: "+fmt.Sprintf("%#v", this.Token)+",\n")
	s = append(s, "Query: "+strings.Replace(this.Query.GoString(), `&`, ``, 1)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringDto(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Move) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Move) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Targets) > 0 {
		for _, msg := range m.Targets {
			dAtA[i] = 0xa
			i++
			i = encodeVarintDto(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	dAtA[i] = 0x12
	i++
	i = encodeVarintDto(dAtA, i, uint64(m.Position.Size()))
	n1, err := m.Position.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	return i, nil
}

func (m *Cast) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Cast) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintDto(dAtA, i, uint64(m.Source.Size()))
	n2, err := m.Source.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	dAtA[i] = 0x12
	i++
	i = encodeVarintDto(dAtA, i, uint64(m.AbilityID.Size()))
	n3, err := m.AbilityID.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n3
	if len(m.Targets) > 0 {
		for k, _ := range m.Targets {
			dAtA[i] = 0x1a
			i++
			v := m.Targets[k]
			msgSize := 0
			if (&v) != nil {
				msgSize = (&v).Size()
				msgSize += 1 + sovDto(uint64(msgSize))
			}
			mapSize := 1 + len(k) + sovDto(uint64(len(k))) + msgSize
			i = encodeVarintDto(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintDto(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintDto(dAtA, i, uint64((&v).Size()))
			n4, err := (&v).MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n4
		}
	}
	return i, nil
}

func (m *Loot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Loot) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintDto(dAtA, i, uint64(m.Source.Size()))
	n5, err := m.Source.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n5
	dAtA[i] = 0x12
	i++
	i = encodeVarintDto(dAtA, i, uint64(m.TargetID.Size()))
	n6, err := m.TargetID.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n6
	dAtA[i] = 0x1a
	i++
	i = encodeVarintDto(dAtA, i, uint64(m.ItemID.Size()))
	n7, err := m.ItemID.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n7
	return i, nil
}

func (m *Consume) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Consume) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintDto(dAtA, i, uint64(m.Source.Size()))
	n8, err := m.Source.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n8
	dAtA[i] = 0x12
	i++
	i = encodeVarintDto(dAtA, i, uint64(m.TargetID.Size()))
	n9, err := m.TargetID.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n9
	dAtA[i] = 0x1a
	i++
	i = encodeVarintDto(dAtA, i, uint64(m.ItemID.Size()))
	n10, err := m.ItemID.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n10
	return i, nil
}

func (m *Query) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Query) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Move != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintDto(dAtA, i, uint64(m.Move.Size()))
		n11, err := m.Move.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n11
	}
	if m.Cast != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintDto(dAtA, i, uint64(m.Cast.Size()))
		n12, err := m.Cast.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n12
	}
	if m.Loot != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintDto(dAtA, i, uint64(m.Loot.Size()))
		n13, err := m.Loot.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n13
	}
	if m.Consume != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintDto(dAtA, i, uint64(m.Consume.Size()))
		n14, err := m.Consume.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n14
	}
	return i, nil
}

func (m *DTO) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DTO) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintDto(dAtA, i, uint64(m.ID.Size()))
	n15, err := m.ID.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n15
	dAtA[i] = 0x12
	i++
	i = encodeVarintDto(dAtA, i, uint64(m.Token.Size()))
	n16, err := m.Token.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n16
	dAtA[i] = 0x1a
	i++
	i = encodeVarintDto(dAtA, i, uint64(m.Query.Size()))
	n17, err := m.Query.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n17
	return i, nil
}

func encodeVarintDto(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func NewPopulatedMove(r randyDto, easy bool) *Move {
	this := &Move{}
	v1 := r.Intn(10)
	this.Targets = make([]github_com_elojah_game_01_pkg_ulid.ID, v1)
	for i := 0; i < v1; i++ {
		v2 := github_com_elojah_game_01_pkg_ulid.NewPopulatedID(r)
		this.Targets[i] = *v2
	}
	v3 := geometry.NewPopulatedPosition(r, easy)
	this.Position = *v3
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedCast(r randyDto, easy bool) *Cast {
	this := &Cast{}
	v4 := github_com_elojah_game_01_pkg_ulid.NewPopulatedID(r)
	this.Source = *v4
	v5 := github_com_elojah_game_01_pkg_ulid.NewPopulatedID(r)
	this.AbilityID = *v5
	if r.Intn(10) != 0 {
		v6 := r.Intn(10)
		this.Targets = make(map[string]ability.Targets)
		for i := 0; i < v6; i++ {
			this.Targets[randStringDto(r)] = *ability.NewPopulatedTargets(r, easy)
		}
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedLoot(r randyDto, easy bool) *Loot {
	this := &Loot{}
	v7 := github_com_elojah_game_01_pkg_ulid.NewPopulatedID(r)
	this.Source = *v7
	v8 := github_com_elojah_game_01_pkg_ulid.NewPopulatedID(r)
	this.TargetID = *v8
	v9 := github_com_elojah_game_01_pkg_ulid.NewPopulatedID(r)
	this.ItemID = *v9
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedConsume(r randyDto, easy bool) *Consume {
	this := &Consume{}
	v10 := github_com_elojah_game_01_pkg_ulid.NewPopulatedID(r)
	this.Source = *v10
	v11 := github_com_elojah_game_01_pkg_ulid.NewPopulatedID(r)
	this.TargetID = *v11
	v12 := github_com_elojah_game_01_pkg_ulid.NewPopulatedID(r)
	this.ItemID = *v12
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedQuery(r randyDto, easy bool) *Query {
	this := &Query{}
	fieldNum := r.Intn(4)
	switch fieldNum {
	case 0:
		this.Move = NewPopulatedMove(r, easy)
	case 1:
		this.Cast = NewPopulatedCast(r, easy)
	case 2:
		this.Loot = NewPopulatedLoot(r, easy)
	case 3:
		this.Consume = NewPopulatedConsume(r, easy)
	}
	return this
}

func NewPopulatedDTO(r randyDto, easy bool) *DTO {
	this := &DTO{}
	v13 := github_com_elojah_game_01_pkg_ulid.NewPopulatedID(r)
	this.ID = *v13
	v14 := github_com_elojah_game_01_pkg_ulid.NewPopulatedID(r)
	this.Token = *v14
	v15 := NewPopulatedQuery(r, easy)
	this.Query = *v15
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyDto interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneDto(r randyDto) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringDto(r randyDto) string {
	v16 := r.Intn(100)
	tmps := make([]rune, v16)
	for i := 0; i < v16; i++ {
		tmps[i] = randUTF8RuneDto(r)
	}
	return string(tmps)
}
func randUnrecognizedDto(r randyDto, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldDto(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldDto(dAtA []byte, r randyDto, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateDto(dAtA, uint64(key))
		v17 := r.Int63()
		if r.Intn(2) == 0 {
			v17 *= -1
		}
		dAtA = encodeVarintPopulateDto(dAtA, uint64(v17))
	case 1:
		dAtA = encodeVarintPopulateDto(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateDto(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateDto(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateDto(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateDto(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *Move) Size() (n int) {
	var l int
	_ = l
	if len(m.Targets) > 0 {
		for _, e := range m.Targets {
			l = e.Size()
			n += 1 + l + sovDto(uint64(l))
		}
	}
	l = m.Position.Size()
	n += 1 + l + sovDto(uint64(l))
	return n
}

func (m *Cast) Size() (n int) {
	var l int
	_ = l
	l = m.Source.Size()
	n += 1 + l + sovDto(uint64(l))
	l = m.AbilityID.Size()
	n += 1 + l + sovDto(uint64(l))
	if len(m.Targets) > 0 {
		for k, v := range m.Targets {
			_ = k
			_ = v
			l = v.Size()
			mapEntrySize := 1 + len(k) + sovDto(uint64(len(k))) + 1 + l + sovDto(uint64(l))
			n += mapEntrySize + 1 + sovDto(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *Loot) Size() (n int) {
	var l int
	_ = l
	l = m.Source.Size()
	n += 1 + l + sovDto(uint64(l))
	l = m.TargetID.Size()
	n += 1 + l + sovDto(uint64(l))
	l = m.ItemID.Size()
	n += 1 + l + sovDto(uint64(l))
	return n
}

func (m *Consume) Size() (n int) {
	var l int
	_ = l
	l = m.Source.Size()
	n += 1 + l + sovDto(uint64(l))
	l = m.TargetID.Size()
	n += 1 + l + sovDto(uint64(l))
	l = m.ItemID.Size()
	n += 1 + l + sovDto(uint64(l))
	return n
}

func (m *Query) Size() (n int) {
	var l int
	_ = l
	if m.Move != nil {
		l = m.Move.Size()
		n += 1 + l + sovDto(uint64(l))
	}
	if m.Cast != nil {
		l = m.Cast.Size()
		n += 1 + l + sovDto(uint64(l))
	}
	if m.Loot != nil {
		l = m.Loot.Size()
		n += 1 + l + sovDto(uint64(l))
	}
	if m.Consume != nil {
		l = m.Consume.Size()
		n += 1 + l + sovDto(uint64(l))
	}
	return n
}

func (m *DTO) Size() (n int) {
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovDto(uint64(l))
	l = m.Token.Size()
	n += 1 + l + sovDto(uint64(l))
	l = m.Query.Size()
	n += 1 + l + sovDto(uint64(l))
	return n
}

func sovDto(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozDto(x uint64) (n int) {
	return sovDto(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Move) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Move{`,
		`Targets:` + fmt.Sprintf("%v", this.Targets) + `,`,
		`Position:` + strings.Replace(strings.Replace(this.Position.String(), "Position", "geometry.Position", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Cast) String() string {
	if this == nil {
		return "nil"
	}
	keysForTargets := make([]string, 0, len(this.Targets))
	for k, _ := range this.Targets {
		keysForTargets = append(keysForTargets, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForTargets)
	mapStringForTargets := "map[string]ability.Targets{"
	for _, k := range keysForTargets {
		mapStringForTargets += fmt.Sprintf("%v: %v,", k, this.Targets[k])
	}
	mapStringForTargets += "}"
	s := strings.Join([]string{`&Cast{`,
		`Source:` + fmt.Sprintf("%v", this.Source) + `,`,
		`AbilityID:` + fmt.Sprintf("%v", this.AbilityID) + `,`,
		`Targets:` + mapStringForTargets + `,`,
		`}`,
	}, "")
	return s
}
func (this *Loot) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Loot{`,
		`Source:` + fmt.Sprintf("%v", this.Source) + `,`,
		`TargetID:` + fmt.Sprintf("%v", this.TargetID) + `,`,
		`ItemID:` + fmt.Sprintf("%v", this.ItemID) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Consume) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Consume{`,
		`Source:` + fmt.Sprintf("%v", this.Source) + `,`,
		`TargetID:` + fmt.Sprintf("%v", this.TargetID) + `,`,
		`ItemID:` + fmt.Sprintf("%v", this.ItemID) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Query) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Query{`,
		`Move:` + strings.Replace(fmt.Sprintf("%v", this.Move), "Move", "Move", 1) + `,`,
		`Cast:` + strings.Replace(fmt.Sprintf("%v", this.Cast), "Cast", "Cast", 1) + `,`,
		`Loot:` + strings.Replace(fmt.Sprintf("%v", this.Loot), "Loot", "Loot", 1) + `,`,
		`Consume:` + strings.Replace(fmt.Sprintf("%v", this.Consume), "Consume", "Consume", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DTO) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DTO{`,
		`ID:` + fmt.Sprintf("%v", this.ID) + `,`,
		`Token:` + fmt.Sprintf("%v", this.Token) + `,`,
		`Query:` + strings.Replace(strings.Replace(this.Query.String(), "Query", "Query", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringDto(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (this *Query) GetValue() interface{} {
	if this.Move != nil {
		return this.Move
	}
	if this.Cast != nil {
		return this.Cast
	}
	if this.Loot != nil {
		return this.Loot
	}
	if this.Consume != nil {
		return this.Consume
	}
	return nil
}

func (this *Query) SetValue(value interface{}) bool {
	switch vt := value.(type) {
	case *Move:
		this.Move = vt
	case *Cast:
		this.Cast = vt
	case *Loot:
		this.Loot = vt
	case *Consume:
		this.Consume = vt
	default:
		return false
	}
	return true
}
func (m *Move) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDto
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Move: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Move: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Targets", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDto
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDto
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_elojah_game_01_pkg_ulid.ID
			m.Targets = append(m.Targets, v)
			if err := m.Targets[len(m.Targets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Position", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDto
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDto
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Position.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDto(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDto
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Cast) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDto
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Cast: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Cast: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDto
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDto
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Source.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AbilityID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDto
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDto
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AbilityID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Targets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDto
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDto
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Targets == nil {
				m.Targets = make(map[string]ability.Targets)
			}
			var mapkey string
			mapvalue := &ability.Targets{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowDto
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowDto
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthDto
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowDto
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= (int(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthDto
					}
					postmsgIndex := iNdEx + mapmsglen
					if mapmsglen < 0 {
						return ErrInvalidLengthDto
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &ability.Targets{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipDto(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthDto
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Targets[mapkey] = *mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDto(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDto
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Loot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDto
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Loot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Loot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDto
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDto
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Source.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDto
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDto
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TargetID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ItemID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDto
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDto
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ItemID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDto(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDto
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Consume) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDto
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Consume: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Consume: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDto
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDto
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Source.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDto
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDto
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TargetID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ItemID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDto
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDto
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ItemID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDto(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDto
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Query) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDto
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Query: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Query: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Move", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDto
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDto
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Move == nil {
				m.Move = &Move{}
			}
			if err := m.Move.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cast", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDto
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDto
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Cast == nil {
				m.Cast = &Cast{}
			}
			if err := m.Cast.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Loot", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDto
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDto
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Loot == nil {
				m.Loot = &Loot{}
			}
			if err := m.Loot.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Consume", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDto
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDto
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Consume == nil {
				m.Consume = &Consume{}
			}
			if err := m.Consume.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDto(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDto
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DTO) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDto
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DTO: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DTO: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDto
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDto
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDto
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDto
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Token.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Query", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDto
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDto
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Query.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDto(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDto
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDto(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDto
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDto
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDto
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthDto
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowDto
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipDto(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthDto = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDto   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("dto.proto", fileDescriptor_dto_1b53a3328885b6b6) }

var fileDescriptor_dto_1b53a3328885b6b6 = []byte{
	// 563 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x54, 0x31, 0x6c, 0xd3, 0x4c,
	0x14, 0xce, 0x8b, 0xed, 0x26, 0xb9, 0x44, 0xbf, 0xaa, 0x9b, 0xac, 0x0c, 0xe7, 0x28, 0xd2, 0x8f,
	0xb2, 0xd4, 0x86, 0x14, 0xa4, 0xa8, 0x12, 0x03, 0x8d, 0x2b, 0x64, 0x51, 0x04, 0x98, 0xec, 0xc8,
	0x49, 0x0f, 0xd7, 0x24, 0xce, 0x05, 0xe7, 0x1c, 0x29, 0x1b, 0x0b, 0x3b, 0x33, 0x13, 0x62, 0x62,
	0x67, 0x61, 0x64, 0xcc, 0xd8, 0x11, 0x31, 0x14, 0x62, 0x16, 0xc6, 0x8e, 0x8c, 0xc8, 0x77, 0x67,
	0x9a, 0xa9, 0x52, 0x23, 0x26, 0xb6, 0xbb, 0xf7, 0xde, 0xf7, 0xee, 0xfb, 0x3e, 0xbf, 0x67, 0x54,
	0x3b, 0xe1, 0xcc, 0x9e, 0x25, 0x8c, 0x33, 0x6c, 0xd0, 0x05, 0x9d, 0xf2, 0xe6, 0x5e, 0x18, 0xf1,
	0xd3, 0x74, 0x68, 0x8f, 0x58, 0xec, 0x84, 0x2c, 0x64, 0x8e, 0xc8, 0x0e, 0xd3, 0xe7, 0xe2, 0x26,
	0x2e, 0xe2, 0x24, 0x51, 0xcd, 0x3b, 0x1b, 0xe5, 0x74, 0xc2, 0x5e, 0x04, 0xa7, 0x4e, 0x18, 0xc4,
	0xf4, 0xd9, 0xcd, 0x5b, 0xce, 0x6c, 0x1c, 0x3a, 0x21, 0x65, 0x31, 0xe5, 0xc9, 0xd2, 0x99, 0xb1,
	0x79, 0xc4, 0x23, 0x36, 0x55, 0xb0, 0xfd, 0xab, 0x61, 0xc1, 0x30, 0x9a, 0x44, 0x7c, 0xe9, 0xf0,
	0x20, 0x09, 0x29, 0x9f, 0x4b, 0x50, 0xfb, 0x35, 0x20, 0xfd, 0x21, 0x5b, 0x50, 0x7c, 0x1f, 0x55,
	0x06, 0x32, 0x63, 0x42, 0x4b, 0xeb, 0x34, 0x0e, 0xf7, 0x56, 0xe7, 0x56, 0xe9, 0xeb, 0xb9, 0xf5,
	0xff, 0xd5, 0x6d, 0xd3, 0x49, 0x74, 0x62, 0x7b, 0xae, 0x5f, 0x51, 0x7d, 0xf1, 0x6d, 0x54, 0x7d,
	0xac, 0x88, 0x99, 0xe5, 0x16, 0x74, 0xea, 0x5d, 0x6c, 0x17, 0x94, 0xed, 0x22, 0x73, 0xa8, 0xe7,
	0xdd, 0xfd, 0x6a, 0x21, 0xa1, 0xfd, 0xbe, 0x8c, 0xf4, 0x7e, 0x30, 0xe7, 0xf8, 0x08, 0xed, 0x3c,
	0x65, 0x69, 0x32, 0xa2, 0x26, 0xb4, 0xe0, 0xfa, 0x34, 0x76, 0xe6, 0x02, 0x8c, 0x1f, 0xa0, 0xda,
	0x3d, 0x29, 0xd8, 0x73, 0x05, 0x8d, 0x6b, 0x77, 0xaa, 0x05, 0x05, 0x1e, 0xf7, 0x2e, 0xbd, 0xd1,
	0x5a, 0x5a, 0xa7, 0xde, 0x35, 0x6d, 0xf1, 0x61, 0xed, 0x9c, 0xb1, 0xad, 0x52, 0x47, 0x53, 0x9e,
	0x2c, 0x95, 0xae, 0xc2, 0x8c, 0xe6, 0x31, 0x6a, 0x6c, 0xa6, 0xf1, 0x2e, 0xd2, 0xc6, 0x74, 0x29,
	0xa4, 0xd5, 0xfc, 0xfc, 0x88, 0x6f, 0x20, 0x63, 0x11, 0x4c, 0x52, 0xaa, 0xbc, 0xda, 0xb5, 0xd5,
	0xb3, 0x45, 0x5b, 0x5f, 0xa6, 0x0f, 0xca, 0x3d, 0x68, 0x7f, 0x03, 0xa4, 0x1f, 0x33, 0xf6, 0xd7,
	0x4c, 0xf2, 0x50, 0x55, 0xbe, 0xb2, 0xad, 0x47, 0x55, 0xae, 0xe0, 0x39, 0x23, 0x8f, 0xd3, 0xd8,
	0x73, 0x4d, 0x6d, 0x2b, 0x46, 0x91, 0x00, 0xb7, 0x33, 0x40, 0x95, 0x3e, 0x9b, 0xce, 0xd3, 0x98,
	0xfe, 0xbb, 0x22, 0xdf, 0x02, 0x32, 0x9e, 0xa4, 0x34, 0x59, 0x62, 0x4b, 0x2e, 0x9f, 0x10, 0x58,
	0xef, 0xd6, 0xd5, 0x54, 0xe5, 0x21, 0x5f, 0x8f, 0xf3, 0xad, 0xb4, 0xe4, 0x56, 0xa8, 0xe1, 0xa8,
	0x6f, 0x8c, 0x9d, 0xaf, 0x8f, 0xf2, 0x75, 0xb1, 0xe4, 0x44, 0x08, 0x42, 0x97, 0x05, 0x79, 0xc8,
	0xd7, 0x27, 0xf9, 0xa8, 0x74, 0xfe, 0x18, 0x6a, 0xea, 0xa2, 0xe6, 0xbf, 0xa2, 0x89, 0x8c, 0xfa,
	0x95, 0x91, 0x3c, 0x1c, 0xe8, 0xab, 0x77, 0x16, 0xb4, 0x3f, 0x02, 0xd2, 0xdc, 0xc1, 0x23, 0x7c,
	0x17, 0x95, 0x3d, 0x77, 0x3b, 0xe7, 0xcb, 0x91, 0x8b, 0xfb, 0xc8, 0x18, 0xb0, 0x31, 0x9d, 0x6e,
	0x67, 0xb9, 0xc1, 0x73, 0x2c, 0xee, 0x28, 0x9f, 0x94, 0xba, 0x86, 0x62, 0x2e, 0x62, 0x6a, 0xd3,
	0x8c, 0x97, 0xe2, 0xd2, 0x3b, 0x5b, 0x93, 0xd2, 0x97, 0x35, 0x29, 0x5d, 0xac, 0x09, 0xfc, 0x5a,
	0x13, 0x78, 0x95, 0x11, 0xf8, 0x90, 0x11, 0xf8, 0x94, 0x11, 0xf8, 0x9c, 0x11, 0x58, 0x65, 0x04,
	0xce, 0x32, 0x02, 0xdf, 0x33, 0x02, 0x3f, 0x33, 0x52, 0xba, 0xc8, 0x08, 0xbc, 0xf9, 0x41, 0x4a,
	0xc3, 0x1d, 0xf1, 0x1f, 0xdc, 0xff, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x51, 0xc1, 0xd1, 0xb6,
	0x05, 0x00, 0x00,
}
